import { Header } from './components'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon.png" />
        <meta name="theme-color" content="#fff" />
      </head>
      <body className="mx-auto font-sans text-grayish-800 dark:text-grayish-200 bg-grayish-200 dark:bg-grayish-800">
        <Header />
        <main className="h-[80vh] px-4 max-md:overflow-y-auto">{children}</main>
      </body>
    </html>
  )
}
